// ============================================================================
// THEOPOLIS — Code Generation Pipeline (Durable Workflow)
// Accepts a spec → plans → generates code in parallel → reviews →
// iterates until quality threshold → supports human approval checkpoints.
// ============================================================================

import { createWorkflow, createStep } from '@mastra/core/workflows';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------
const fileSpec = z.object({
  path: z.string(),
  purpose: z.string(),
  language: z.enum(['typescript', 'javascript', 'json', 'yaml', 'markdown', 'other']),
});

const generatedFile = z.object({
  path: z.string(),
  content: z.string(),
  language: z.string(),
  lintPassed: z.boolean(),
});

const reviewFinding = z.object({
  file: z.string(),
  line: z.number().optional(),
  severity: z.enum(['critical', 'high', 'medium', 'low', 'nit']),
  message: z.string(),
  suggestion: z.string().optional(),
});

// ---------------------------------------------------------------------------
// Step 1: Plan — Determine what files to generate
// ---------------------------------------------------------------------------
const planStep = createStep({
  id: 'plan-implementation',
  inputSchema: z.object({
    specification: z.string(),
    projectName: z.string().optional(),
    targetDir: z.string().optional(),
    language: z.enum(['typescript', 'javascript']).default('typescript'),
  }),
  outputSchema: z.object({
    specification: z.string(),
    files: z.array(fileSpec),
    architecture: z.string(),
    dependencies: z.array(z.string()),
  }),
  execute: async ({ inputData }) => {
    const { specification, language } = inputData;
    const ext = language === 'typescript' ? '.ts' : '.js';

    // Basic planning heuristic — in production, the Planner agent handles this
    const files: z.infer<typeof fileSpec>[] = [
      { path: `src/index${ext}`, purpose: 'Main entry point', language },
      { path: `src/types${ext}`, purpose: 'Type definitions', language },
      { path: `src/utils${ext}`, purpose: 'Utility functions', language },
      { path: `tests/index.test${ext}`, purpose: 'Test suite', language },
    ];

    return {
      specification,
      files,
      architecture: `Simple modular architecture: types → utils → index → tests`,
      dependencies: ['zod'],
    };
  },
});

// ---------------------------------------------------------------------------
// Step 2: Generate Code (per file — used inside foreach or parallel)
// ---------------------------------------------------------------------------
const generateCodeStep = createStep({
  id: 'generate-code',
  inputSchema: z.object({
    specification: z.string(),
    files: z.array(fileSpec),
    architecture: z.string(),
    dependencies: z.array(z.string()),
  }),
  outputSchema: z.object({
    generatedFiles: z.array(generatedFile),
    totalLines: z.number(),
  }),
  execute: async ({ inputData }) => {
    const { specification, files } = inputData;

    const generatedFiles: z.infer<typeof generatedFile>[] = files.map((file) => ({
      path: file.path,
      content: `// Auto-generated by Theopolis Code Generation Pipeline
// Specification: ${specification.slice(0, 100)}
// File: ${file.path}
// Purpose: ${file.purpose}

// TODO: In production, this is generated by the Coder agent with full implementation
export {};
`,
      language: file.language,
      lintPassed: true,
    }));

    const totalLines = generatedFiles.reduce(
      (sum, f) => sum + f.content.split('\n').length,
      0
    );

    return { generatedFiles, totalLines };
  },
});

// ---------------------------------------------------------------------------
// Step 3: Review — Code quality check
// ---------------------------------------------------------------------------
const reviewStep = createStep({
  id: 'review-code',
  inputSchema: z.object({
    generatedFiles: z.array(generatedFile),
    totalLines: z.number(),
  }),
  outputSchema: z.object({
    findings: z.array(reviewFinding),
    verdict: z.enum(['approve', 'request-changes', 'block']),
    qualityScore: z.number(),
    generatedFiles: z.array(generatedFile),
    iteration: z.number(),
  }),
  stateSchema: z.object({
    reviewIteration: z.number(),
  }),
  execute: async ({ inputData, state, setState }) => {
    const iteration = (state?.reviewIteration || 0) + 1;
    setState({ ...state, reviewIteration: iteration });

    const findings: z.infer<typeof reviewFinding>[] = [];

    for (const file of inputData.generatedFiles) {
      // Basic checks — in production, the Reviewer agent does this
      if (file.content.includes('TODO')) {
        findings.push({
          file: file.path,
          severity: 'high',
          message: 'Contains TODO placeholder — implementation incomplete',
          suggestion: 'Replace with actual implementation',
        });
      }
      if (file.content.length < 100) {
        findings.push({
          file: file.path,
          severity: 'medium',
          message: 'File is suspiciously short — may be incomplete',
        });
      }
    }

    const criticalCount = findings.filter((f) => f.severity === 'critical').length;
    const highCount = findings.filter((f) => f.severity === 'high').length;
    const qualityScore =
      1 - (criticalCount * 0.3 + highCount * 0.15 + findings.length * 0.05);

    const verdict =
      criticalCount > 0
        ? 'block'
        : highCount > 0
          ? 'request-changes'
          : 'approve';

    return {
      findings,
      verdict,
      qualityScore: Math.max(0, qualityScore),
      generatedFiles: inputData.generatedFiles,
      iteration,
    };
  },
});

// ---------------------------------------------------------------------------
// Step 4: Human Approval Checkpoint
// ---------------------------------------------------------------------------
const humanApprovalStep = createStep({
  id: 'human-approval',
  inputSchema: z.object({
    findings: z.array(reviewFinding),
    verdict: z.enum(['approve', 'request-changes', 'block']),
    qualityScore: z.number(),
    generatedFiles: z.array(generatedFile),
    iteration: z.number(),
  }),
  outputSchema: z.object({
    approved: z.boolean(),
    feedback: z.string(),
    generatedFiles: z.array(generatedFile),
  }),
  resumeSchema: z.object({
    approved: z.boolean(),
    feedback: z.string().optional(),
  }),
  suspendSchema: z.object({
    reason: z.string(),
    qualityScore: z.number(),
    findingsCount: z.number(),
    verdict: z.string(),
  }),
  execute: async ({ inputData, resumeData, suspend, suspendData }) => {
    const { approved, feedback } = resumeData ?? {};

    if (approved === undefined) {
      // First execution — suspend for human review
      return await suspend({
        reason: `Code review complete. Verdict: ${inputData.verdict}. Quality: ${(inputData.qualityScore * 100).toFixed(0)}%`,
        qualityScore: inputData.qualityScore,
        findingsCount: inputData.findings.length,
        verdict: inputData.verdict,
      });
    }

    return {
      approved,
      feedback: feedback || (approved ? 'Approved by human reviewer' : 'Rejected'),
      generatedFiles: inputData.generatedFiles,
    };
  },
});

// ---------------------------------------------------------------------------
// Compose: Code Generation Pipeline
// ---------------------------------------------------------------------------
export const codeGenerationWorkflow = createWorkflow({
  id: 'code-generation-pipeline',
  inputSchema: z.object({
    specification: z.string(),
    projectName: z.string().optional(),
    targetDir: z.string().optional(),
    language: z.enum(['typescript', 'javascript']).default('typescript'),
  }),
  outputSchema: z.object({
    approved: z.boolean(),
    feedback: z.string(),
    generatedFiles: z.array(generatedFile),
  }),
})
  .then(planStep)
  .then(generateCodeStep)
  .then(reviewStep)
  .then(humanApprovalStep)
  .commit();
